### ISSUE TITLE
Download Bug

### ISSUE THREAD

**Issue by turnerthestud** [slashme/parliamentdiagram#84]
I am unable to create a diagram on my Mac or iPhone. On my Mac it if I click on the US Style it just gives me enlarged images. I think the diagram button is just not working, on the Mac it isn't blue or looks like it can even be pressed.

**Comment by slashme** [comment]
Thank you for the report!!

I just changed some CSS code, hoping that it would be an improvement, but I guess I made it incompatible with some browsers: I don't have any Apple devices to test it on. I'll revert the changes tonight when I get home. 

Can you add some screenshots of what it looks like?

**Comment by slashme** [comment]
OK, I think this should now be fixed, because I reverted back to the way it was before I made the changes. Please let me know if it works for you now!

**Comment by turnerthestud** [comment]
Hi David, 

I just checked and it’s still doing the same thing for safari on iPhone and on the Mac. Here’s what it looks like at the bottom of the page for the Mac, the make my diagram button still doesn’t work. Thank you for looking into this! 


Turner Hubby

**Comment by slashme** [comment]
Hmm, somehow the screenshot didn't make it to github. You can send it to me by mail at davidrichfield@gmail.com.

Did the site work for you previously?

**Comment by slashme** [comment]
Ah, now I understand what's happening! I updated the script to allow the user to add adjustable borders to the spots, but never remembered to upgrade the old US-specific interface. I'll fix that now, shouldn't take very long. 

But may I interest you in the feature of grabbing the list of parties from an existing diagram? If you go to https://parliamentdiagram.toolforge.org/parlitest.php and enter "https://parliamentdiagram.toolforge.org/parlitest.php" in the box marked "get list of parties from" and click "get party list", it will give you the list of parties used in that diagram. This works on any diagram where the file description has a party list created by the parliament generator script.

**Comment by slashme** [comment]
OK, I think it should work now. If it gives the enlarged images, try reloading. I'm busy trying to find the cause of that bug now.

**Comment by slashme** [comment]
Right, I found the bug: I had moved the CSS files into a separate directory a while ago, and forgot to update this script. Please let me know if I can close this issue now.

**Comment by turnerthestud** [comment]
Yes it works! Thank you so much!

Turner Hubby
